//! UI translations with Project Fluent (`fluent-bundle`).
//!
//! The `.ftl` files in `i18n/` are embedded in the binary. `build.rs`
//! validates them and generates [`t`], one typed function per English
//! message, so the UI never refers to messages by string:
//! `t::menu_file_new(shortcut_display(Shortcut::New))`.
//!
//! Lookups go to the current language first and fall back to English for
//! messages it does not translate yet. Switching language replaces the
//! current bundles; Iced rebuilds the view from state, so the change shows
//! on the next frame without a restart.

use std::borrow::Cow;
use std::fmt;
use std::str::FromStr;

use fluent_bundle::concurrent::FluentBundle;
use fluent_bundle::{FluentArgs, FluentResource};
use unic_langid::LanguageIdentifier;

/// One function per message in `i18n/en.ftl`, generated by `build/i18n.rs`.
pub mod t {
    use fluent_bundle::{FluentArgs, FluentValue};

    include!(concat!(env!("OUT_DIR"), "/i18n_messages.rs"));
}

const ENGLISH_FTL: &str = include_str!("../i18n/en.ftl");
const SPANISH_FTL: &str = include_str!("../i18n/es.ftl");
const PORTUGUESE_BR_FTL: &str = include_str!("../i18n/pt-BR.ftl");
const RUSSIAN_FTL: &str = include_str!("../i18n/ru.ftl");

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Language {
    English,
    Spanish,
    PortugueseBr,
    Russian,
    /// English with accented, lengthened text, for finding labels that
    /// clip or wrap before real translations arrive. Debug builds only.
    Pseudo,
}

impl Language {
    /// The languages offered in the Language menu, in menu order.
    pub const SELECTABLE: [Language; 4] = [
        Language::English,
        Language::Spanish,
        Language::PortugueseBr,
        Language::Russian,
    ];

    /// The code stored in settings.ini.
    pub const fn code(self) -> &'static str {
        match self {
            Language::English => "en",
            Language::Spanish => "es",
            Language::PortugueseBr => "pt-BR",
            Language::Russian => "ru",
            Language::Pseudo => "pseudo",
        }
    }

    /// The language's name in that language, so a user can find their own
    /// language whatever the current one is.
    pub const fn autonym(self) -> &'static str {
        match self {
            Language::English => "English",
            Language::Spanish => "Español",
            Language::PortugueseBr => "Português (Brasil)",
            Language::Russian => "Русский",
            Language::Pseudo => "Pseudo",
        }
    }

    /// Whether the Bricolage display font covers this language's letters;
    /// it has no Cyrillic, so Russian headings use Inter instead.
    pub const fn display_font_covers(self) -> bool {
        !matches!(self, Language::Russian)
    }

    /// Match a BCP 47 / POSIX locale tag (`es-MX`, `ru_RU.UTF-8`) by its
    /// primary language subtag.
    pub fn from_locale_tag(tag: &str) -> Option<Language> {
        let primary = tag.split(['-', '_', '.']).next()?.to_ascii_lowercase();
        match primary.as_str() {
            "en" => Some(Language::English),
            "es" => Some(Language::Spanish),
            "pt" => Some(Language::PortugueseBr),
            "ru" => Some(Language::Russian),
            _ => None,
        }
    }

    fn source(self) -> &'static str {
        match self {
            Language::English | Language::Pseudo => ENGLISH_FTL,
            Language::Spanish => SPANISH_FTL,
            Language::PortugueseBr => PORTUGUESE_BR_FTL,
            Language::Russian => RUSSIAN_FTL,
        }
    }

    /// The locale used for plural rules and number formatting.
    fn locale(self) -> LanguageIdentifier {
        let tag = match self {
            Language::English | Language::Pseudo => "en",
            Language::Spanish => "es",
            Language::PortugueseBr => "pt-BR",
            Language::Russian => "ru",
        };
        tag.parse().expect("built-in locale tags are valid")
    }
}

/// The saved language choice: follow Windows, or a fixed language.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum LanguageSetting {
    #[default]
    System,
    Fixed(Language),
}

impl LanguageSetting {
    pub fn resolve(self) -> Language {
        match self {
            LanguageSetting::System => system_language(),
            // A pseudo setting copied into a release build shows English.
            LanguageSetting::Fixed(Language::Pseudo) if !cfg!(debug_assertions) => {
                Language::English
            }
            LanguageSetting::Fixed(language) => language,
        }
    }
}

impl fmt::Display for LanguageSetting {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LanguageSetting::System => f.write_str("auto"),
            LanguageSetting::Fixed(language) => f.write_str(language.code()),
        }
    }
}

impl FromStr for LanguageSetting {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim() {
            "auto" => Ok(LanguageSetting::System),
            "pseudo" => Ok(LanguageSetting::Fixed(Language::Pseudo)),
            code => Language::SELECTABLE
                .into_iter()
                .find(|language| language.code() == code)
                .map(LanguageSetting::Fixed)
                .ok_or(()),
        }
    }
}

/// The Windows display language, when it is one the app supports.
pub fn system_language() -> Language {
    // Tests must not depend on the machine running them.
    if cfg!(test) {
        return Language::English;
    }
    sys_locale::get_locale()
        .as_deref()
        .and_then(Language::from_locale_tag)
        .unwrap_or(Language::English)
}

/// Formats messages for one language, falling back to English.
pub(crate) struct Localizer {
    language: Language,
    primary: FluentBundle<FluentResource>,
    fallback: Option<FluentBundle<FluentResource>>,
}

impl Localizer {
    pub(crate) fn new(language: Language) -> Self {
        let fallback = (!matches!(language, Language::English | Language::Pseudo))
            .then(|| bundle(Language::English));
        Self {
            language,
            primary: bundle(language),
            fallback,
        }
    }

    pub(crate) fn format(&self, id: &str, args: Option<&FluentArgs>) -> String {
        for bundle in std::iter::once(&self.primary).chain(self.fallback.as_ref()) {
            let Some(pattern) = bundle.get_message(id).and_then(|message| message.value()) else {
                continue;
            };
            let mut errors = Vec::new();
            let text = bundle.format_pattern(pattern, args, &mut errors);
            if !errors.is_empty() {
                log::warn!("i18n: formatting `{id}` in {:?}: {errors:?}", self.language);
            }
            return text.into_owned();
        }
        // Unreachable for generated calls: build.rs derives them from en.ftl.
        id.to_string()
    }
}

fn bundle(language: Language) -> FluentBundle<FluentResource> {
    let mut bundle = FluentBundle::new_concurrent(vec![language.locale()]);
    // Fluent wraps placeables in Unicode bidi isolation marks by default;
    // every supported language is left-to-right and Iced would draw the
    // marks as stray glyphs.
    bundle.set_use_isolating(false);
    if language == Language::Pseudo {
        bundle.set_transform(Some(pseudo_transform));
    }
    // build.rs rejects syntax errors and duplicate ids, so neither the parse
    // nor the insert can fail at runtime.
    let resource = FluentResource::try_new(language.source().to_owned())
        .unwrap_or_else(|(resource, _)| resource);
    let _ = bundle.add_resource(resource);
    bundle
}

/// Pseudo-localization: accent every letter (from Latin-1, which all the
/// bundled fonts cover) and double the vowels, which lengthens typical UI
/// English by roughly a third, like Spanish or Russian text.
fn pseudo_transform(text: &str) -> Cow<'_, str> {
    let mut out = String::with_capacity(text.len() * 2);
    for character in text.chars() {
        let (accented, doubled) = match character {
            'a' => ('á', true),
            'e' => ('é', true),
            'i' => ('í', true),
            'o' => ('ó', true),
            'u' => ('ú', true),
            'A' => ('Á', true),
            'E' => ('É', true),
            'I' => ('Í', true),
            'O' => ('Ó', true),
            'U' => ('Ú', true),
            'c' => ('ç', false),
            'n' => ('ñ', false),
            'y' => ('ý', false),
            'C' => ('Ç', false),
            'N' => ('Ñ', false),
            'Y' => ('Ý', false),
            other => (other, false),
        };
        out.push(accented);
        if doubled {
            out.push(accented);
        }
    }
    Cow::Owned(out)
}

// The current language. The app shares one; unit tests run on parallel
// threads, so each test thread gets its own, starting in English.
#[cfg(not(test))]
static CURRENT: std::sync::LazyLock<std::sync::RwLock<Localizer>> =
    std::sync::LazyLock::new(|| std::sync::RwLock::new(Localizer::new(Language::English)));

#[cfg(test)]
thread_local! {
    static CURRENT: std::cell::RefCell<Localizer> =
        std::cell::RefCell::new(Localizer::new(Language::English));
}

#[cfg(not(test))]
fn with_current<T>(read: impl FnOnce(&Localizer) -> T) -> T {
    read(
        &CURRENT
            .read()
            .unwrap_or_else(|poisoned| poisoned.into_inner()),
    )
}

#[cfg(test)]
fn with_current<T>(read: impl FnOnce(&Localizer) -> T) -> T {
    CURRENT.with(|current| read(&current.borrow()))
}

/// Switch the UI language.
pub fn set_language(language: Language) {
    let localizer = Localizer::new(language);
    #[cfg(not(test))]
    {
        *CURRENT
            .write()
            .unwrap_or_else(|poisoned| poisoned.into_inner()) = localizer;
    }
    #[cfg(test)]
    CURRENT.with(|current| *current.borrow_mut() = localizer);
}

/// The language the UI is currently shown in.
pub fn current() -> Language {
    with_current(|localizer| localizer.language)
}

/// Used by the generated [`t`] functions.
fn format(id: &str, args: Option<&FluentArgs>) -> String {
    with_current(|localizer| localizer.format(id, args))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_english_message_formats_in_every_language() {
        for language in [
            Language::English,
            Language::Spanish,
            Language::PortugueseBr,
            Language::Russian,
            Language::Pseudo,
        ] {
            let localizer = Localizer::new(language);
            for id in t::MESSAGE_IDS {
                let text = localizer.format(id, None);
                assert!(!text.is_empty(), "{id} is empty in {language:?}");
                assert_ne!(&text, id, "{id} did not resolve in {language:?}");
            }
        }
    }

    #[test]
    fn switching_language_changes_generated_lookups() {
        assert_eq!(t::menu_file(), "File");
        set_language(Language::Spanish);
        assert_eq!(t::menu_file(), "Archivo");
        assert_eq!(t::menu_file_new("Ctrl + N"), "Nuevo (Ctrl + N)");
        set_language(Language::PortugueseBr);
        assert_eq!(t::menu_file(), "Arquivo");
        assert_eq!(t::menu_file_new("Ctrl + N"), "Novo (Ctrl + N)");
        set_language(Language::Russian);
        assert_eq!(t::menu_file(), "Файл");
        set_language(Language::English);
        assert_eq!(current(), Language::English);
    }

    #[test]
    fn russian_plurals_follow_cldr_categories() {
        set_language(Language::Russian);
        assert_eq!(t::context_more_selected(1), "ещё 1 выбранный элемент");
        assert_eq!(t::context_more_selected(3), "ещё 3 выбранных элемента");
        assert_eq!(t::context_more_selected(5), "ещё 5 выбранных элементов");
        assert_eq!(t::context_more_selected(11), "ещё 11 выбранных элементов");
        assert_eq!(t::context_more_selected(21), "ещё 21 выбранный элемент");
        assert_eq!(t::context_more_selected(22), "ещё 22 выбранных элемента");
        set_language(Language::English);
    }

    #[test]
    fn plurals_and_multiline_messages_format_as_written() {
        assert_eq!(
            t::bulk_entry("a.txd", 1, "DXT1"),
            "a.txd - 1 texture -> DXT1"
        );
        assert_eq!(
            t::bulk_entry("a.txd", 3, "DXT1"),
            "a.txd - 3 textures -> DXT1"
        );
        assert_eq!(
            t::unsaved_window(2, "gta3, player"),
            "2 archives have unsaved changes: gta3, player"
        );
        // Blank lines inside a multi-line message survive parsing.
        let about = t::about_body("9.9.9");
        assert!(
            about.starts_with("IMG Editor Plus v9.9.9\n\nA pure Rust"),
            "{about}"
        );
        assert!(about.ends_with("- Bully Scholarship Edition"), "{about}");
        set_language(Language::Spanish);
        assert_eq!(
            t::bulk_entry("a.txd", 1, "DXT1"),
            "a.txd - 1 textura -> DXT1"
        );
        set_language(Language::English);
    }

    #[test]
    fn sort_keys_show_translated_but_persist_in_english() {
        set_language(Language::Russian);
        assert_eq!(crate::sort::SortKey::Size.to_string(), "Размер");
        assert_eq!(crate::sort::SortKey::Size.display_name(), "Size");
        set_language(Language::English);
    }

    #[test]
    fn placeables_carry_no_bidi_isolation_marks() {
        let mut args = FluentArgs::new();
        args.set("shortcut", "Ctrl + N");
        let text = Localizer::new(Language::English).format("menu-file-new", Some(&args));
        assert_eq!(text, "New (Ctrl + N)");
        assert!(!text.contains(['\u{2068}', '\u{2069}']));
    }

    #[test]
    fn pseudo_locale_accents_and_lengthens_text_but_not_arguments() {
        let localizer = Localizer::new(Language::Pseudo);
        let mut args = FluentArgs::new();
        args.set("shortcut", "Ctrl + N");
        let text = localizer.format("menu-file-new", Some(&args));
        assert!(text.starts_with("Ñééw ("), "{text}");
        assert!(text.ends_with("(Ctrl + N)"), "{text}");
    }

    #[test]
    fn settings_round_trip_and_locale_tags_match() {
        for setting in [
            LanguageSetting::System,
            LanguageSetting::Fixed(Language::English),
            LanguageSetting::Fixed(Language::Spanish),
            LanguageSetting::Fixed(Language::PortugueseBr),
            LanguageSetting::Fixed(Language::Russian),
        ] {
            assert_eq!(setting.to_string().parse(), Ok(setting));
        }
        assert_eq!("fr".parse::<LanguageSetting>(), Err(()));
        assert_eq!(Language::from_locale_tag("es-MX"), Some(Language::Spanish));
        assert_eq!(
            Language::from_locale_tag("pt_BR.UTF-8"),
            Some(Language::PortugueseBr)
        );
        assert_eq!(
            Language::from_locale_tag("ru_RU.UTF-8"),
            Some(Language::Russian)
        );
        assert_eq!(Language::from_locale_tag("en-GB"), Some(Language::English));
        assert_eq!(Language::from_locale_tag("fr-FR"), None);
    }
}
